### PR TITLE
fix: remove game helpers #211

### LINKED ISSUE #211: Players obtained from game.getPlayers() do not function the same as the player prop (no .get())
In the `callbacks.js`, in `Empirica.onStageEnd`, I am trying to get and set information to a player. The `player `isn't a parameter of this callback, but we can get the Players with `game.getPlayers()`. However, these players do not function the same way as `player `as a prop; you cannot use `.get()` and `.set()`. I would suppose that it should be more consistent. I can access the information by getting the `player.data`. I suppose I can set it there and it might update the `player` prop, but I am not sure. If there is a way of making this consistent with how it works with the props (and, see below, how it worked before).
This is with `empirica:core 1.13.0 `

I have another project, with` empirica:core 1.11.1` where I could successfully use `game.players` to access the players, and where once I selected the players I could use `.get()` and `.set()`. Although this was not in a _callback_, I don't see why it would be different? 
I think `game `was changed? 

Thank you for your help.

### PR DESCRIPTION
**Pull request by hubertusputu1**
Removed game helpers.

## Motivation and Context

#211 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: api/games/augment.js [hunk 1]
```diff
@@ -27,10 +29,10 @@ export const augmentGameObject = ({
     players: {
       get() {
         if (!gamePlayers) {
-          gamePlayers = game.getPlayers();
+          gamePlayers = Players.find({ _id: { $in: game.playerIds } }).fetch();
 
           if (firstRoundId) {
-            round = game.getRounds().find(r => r._id === firstRoundId);
+            round = Rounds.find({ firstRoundId }).fetch();
```
Comment (npaton) [inline api/games/augment.js]: Is this correct? Shouldn't it be something like:
```suggestion
            round = Rounds.findOne(firstRoundId).fetch();
```

**Review by npaton — CHANGES_REQUESTED** [review]

File: api/games/augment.js (hunk 1 above)
Comment (hubertusputu1) [reply api/games/augment.js]: My apologize , i have fixed that one.

**Review by npaton — APPROVED** [review]
