### PR TITLE
fix: splitting params on callback #142

### LINKED ISSUE #142: Bug on splitting parameters on game callback
doing the game.set('key', 'value') inside onGameStart callback will produce an error

## Steps to Reproduce (for bugs)

1. doing a game.set() on onGameStart callback

## Your Environment

- Version used:
meteor-empirica-core: 1.6.0

### PR DESCRIPTION
**Pull request by hubertusputu1**
fix splitting params on game callback

## Description

fix the code when splitting params

## Motivation and Context

#142 

## How Has This Been Tested?

- tested by passing normal params on game callback
- tested by passing unintended param ("players") on game callback, the error message is shown

 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -48,19 +48,20 @@ export const isReactComponents = components => {
   return isValid;
 };
 
-var STRIP_COMMENTS = /((\/\/.*$)|(\/\*[\s\S]*?\*\/))/gm;
-var ARGUMENT_NAMES = /(?:^|,)\s*([^\s,=]+)/g;
+let STRIP_COMMENTS = /((\/\/.*$)|(\/\*[\s\S]*?\*\/))/gm;
```
Comment (npaton) [inline lib/utils.js:51]: All these `let`s are consts (except for fnStr and the let in the for loop), no?

**Review by npaton — APPROVED** [review]
