### PR TITLE
fix: send queued players to exit when batch is cancelled #233

### LINKED ISSUE #233: Players are still in the game when batch is cancelled
Game is created with multiple players. when we cancelled the batch when they are in introductions, they don't go on exit page. They can still go through introduction and make it lobby page. 

## Expected Behavior

Players should go to exit page if batch is cancelled.

## Current Behavior

Players stay on the game and continue to the lobby.

### PR DESCRIPTION
**Pull request by hubertusputu1**
make queued players on gameLobbies go to exit if batch is cancelled

## Motivation and Context

#233 

## How Has This Been Tested?

Create a game and player stay on the intro pages, cancelled the batch from the admin. players go to exit page.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by hubertusputu1** [comment]
@npaton i wonder if should we move the players into the available batch (if there is any) before we kicked them out?

**Review by npaton — DISMISSED** [review]
Looks good if was tested 👍

**Comment by hubertusputu1** [comment]
@npaton Sorry, i put fixes on the last commit. Before it is fixed, when the batch is cancelled the players won't go to exit page if they are already on a round state.

File: api/batches/hooks.js [hunk 1]
```diff
@@ -99,29 +100,38 @@ Batches.after.update(
...
+      batchId,
+      gameId: { $exists: false }
+    }).fetch();
+
+    if (gameLobbies.length === 0) {
+      return;
     }
+
+    const glplayerIds = _.flatten(_.pluck(gameLobbies, "queuedPlayerIds"));
+    const players = Players.find({
```
Comment (npaton) [inline api/batches/hooks.js:127]: I guess we could check glplayerIds.length > 0 here. The game lobbies might all have 0 players. I think the Players.find will just return nothing, though I don't know, maybe it will throw. 👯

**Review by npaton — APPROVED** [review]

File: api/batches/hooks.js (hunk 1 above)
Comment (npaton) [reply api/batches/hooks.js:127]: Tested, does not throw 👍
