### PR TITLE
fix: fixed exitSteps undefined

### LINKED ISSUE #77: Default exit steps fail when Empirica.exitSteps is not defined
This isn't something that is likely to come up often, but:

## Expected Behavior
Documentation in `client/main.js` says:
> If you don't return anything, or do not define this function, a default exit screen will be shown.

## Current Behavior
No default exit screen is produced, the following errors are raised:

image

This occurs either if
```javascript
Empirica.exitSteps((game, player) => {
  //return [ExitSurvey, Thanks];
});
```
or
```javascript
//Empirica.exitSteps((game, player) => {
  //return [ExitSurvey, Thanks];
//});
```
but does not fail if:
```javascript
Empirica.exitSteps((game, player) => {
  return []
  //return [ExitSurvey, Thanks];
});
```

## Steps to Reproduce (for bugs)
Generated in the template project that is created by:
```bash
npx create-empirica-app empirica_demo
```

## Context
I commented these out because it smooths the dev process to be able to skip intro and exit screens. It's not really a problem not to have a default exit screen, but it's not the promised behavior.

## Your Environment
- Version used: 1.3.4

### PR DESCRIPTION
**Pull request by hubertusputu1**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: ui/components/Game.jsx [hunk 1]
```diff
@@ -39,8 +39,7 @@ export default class Game extends React.Component {
     }
 
     if (player.exitAt) {
-      const steps = exitSteps && exitSteps(game, player);
-
+      const steps = exitSteps(game, player) ? exitSteps(game, player) : [];
```
Comment (npaton) [inline ui/components/Game.jsx]: You don't need to call `existSteps()` twice here (unnecessary computation), you can simply do an `||` instead of using a ternary operator.
`const steps = exitSteps(game, player) || [];`

**Review by npaton — CHANGES_REQUESTED** [review]
There's quick change needed. Could you also make sure introSteps can be omitted as well while we're add it. 👍

File: lib/utils.js [hunk 2]
```diff
@@ -16,3 +23,27 @@ export const weightedRandom = values => {
 
   return () => samples[Math.floor(Math.random() * samples.length)];
 };
+
+export const isReactComponents = components => {
+  let isValid = true;
+
+  if (components && _.isArray(components) && components.length > 0) {
+    components.forEach(component => {
```
Comment (npaton) [inline lib/utils.js]: Anytime you can exit a loop early (here for example you can stop iterating as soon as you find one invalid "component"), you should use a classic for loop (`for (...;...;...) { ... }`), which you can interrupt early with a `break` or `return`. With forEach, you can't interrupt the loop execution and run through items needlessly. It's probably not a noticeable performance impact here, but it adds up, and in other places it might have an impact, so it's good to have the habit.

File: client.js [hunk 3]
```diff
@@ -1,4 +1,5 @@
 import React from "react";
+import _ from "lodash";
```
Comment (npaton) [inline client.js]: We already have the `underscore` dependency, lets not add lodash. It is added as a global at the moment, not ideal, and lodash would generally be better, but it's here for historical reasons and I'm afraid we might break people's apps if we change this now. All you need to do here is just remove this lodash import and remove the dependency.

File: client.js [hunk 4]
```diff
@@ -41,11 +47,19 @@ const Empirica = {
   },
 
   introSteps(func) {
-    config.introSteps = func;
+    if (!_.isFunction(func)) {
+      throw new Error("introSteps requires a function");
+    }
+
+    config.introSteps = isReactComponents(func()) ? func : () => [];
```
Comment (npaton) [inline client.js]: This will not work. The function passed to `Empirica.introSteps` expects to receive game and treatment as arguments. Here, you're calling the function without these arguments (because at this point, you do not have those objects, we're before any game has started). The check must be done at runtime, not init as you do here.

```js
    config.introSteps = function() {
      const results = func.apply(null, arguments);
      if (isReactComponents(results)) {
        return results;
      }   else {
        console.error("Empirica.introSteps() is not returning an array of components as expected.");
        return [];
      }
   }
```

This is the same for exist steps.

File: lib/utils.js [hunk 5]
```diff
@@ -16,3 +23,27 @@ export const weightedRandom = values => {
 
   return () => samples[Math.floor(Math.random() * samples.length)];
 };
+
+export const isReactComponents = components => {
+  let isValid = true;
+
+  if (components && _.isArray(components) && components.length > 0) {
```
Comment (npaton) [inline lib/utils.js]: We should allow components to be an empty array, so drop the length check here.

File: client.js (hunk 4 above)
Comment (npaton) [reply client.js]: Actually, we should also support null/undefined results here. So "maybe" something more like this:

```js
    config.introSteps = function() {
      const results = func.apply(null, arguments);
      if (!results || isReactComponents(results)) {
        return results || [];
      }   else {
        console.error("Empirica.introSteps() is not returning an array of components as expected.");
        return [];
      }
    }
```

**Review by npaton — CHANGES_REQUESTED** [review]
@hubertusputu1 Quite a few changes, nothing difficult I believe, should not take you long (do make sure to test though). Sorry, they are mostly things I did not make clear, or you did not know about. Let me know if you have any questions.

File: lib/utils.js (hunk 2 above)
Comment (hubertusputu1) [reply lib/utils.js]: thanks for the suggestion. should we always use classic loop for array? or can we just use `forEach` loop if there is no need to use `break` statement?

Comment (npaton) [reply lib/utils.js]: I think the classic loop is not that complicated, and it avoids the closure scoping + the function calls, so it's undeniably less computation, and it allows for break/return, so there are not many downsides. That said, with modern JS runtimes like V8, and small collections to loop over, forEach is fine. So just do this, if you know it's in a critical path (during user interaction on browser for example), or that the number of items to loop over is large, or the closure context is large (many local vars that will be captured by the closure), go for classic, otherwise forEach is ok.
Damn, this is answer is longer than you should think about the problem. That's why I do classic 99% of the time, just don't need to think about it. 😆

Comment (hubertusputu1) [reply lib/utils.js]: indeed it is a long answer 😃 but thanks for the answers.

**Review by npaton — APPROVED** [review]
LGTM ⛵️
