### PR TITLE
fix: save intro states of each player #230

### LINKED ISSUE #230: Intro resets when the batch starts
When participants are reading the instructions (they are in the opaque state in the batches) and the batch starts, the instruction that the participants are reading refreshes and the page goes to the first page.

## Expected Behavior

Participants should be able to keep reading the instructions without returning to the first page in the instruction.

## Current Behavior

Participants return to the first page when the batch they were originally assigned to starts, perhaps due to them moving to another batch.

## Possible Solution

I do not have a possible solution, sorry!

## Steps to Reproduce (for bugs)

1. I used Abdullah's CSOP experiment (http://github.com/amaatouq/room-assignment-csop/) locally to observe this behavior.
2. After setting up a configuration using `example-config.yaml` file in the directory, start two batches using the "team" treatment, one game each.
3. Start a new player, move to the quiz page but do not solve the quiz.
4. Start three additional players, submit the quiz (answer should be 3, "We will submit only one answer as a team and therefore we will all get the same score.", 0, 100, Room 102, Room 102/104) for the additional players.
5. The game starts for the latter three players, but the instruction page goes to the initial page for the first player who did not submit the quiz yet.

## Context

The instruction for the task is quite long, so participants get frustrated and leave the task without participating (and sometimes send angry emails). Thus, it makes the attrition rate of participant go up, negatively impacting research.

## Your Environment

- Version used: empiricia:core 1.15.2 / empricia:slider: 0.0.3
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 88.0.4324.96, node.js 12.21.0
- Operating System and version (desktop or mobile): desktop, Ubuntu 20.04.1
- Link to your project: http://github.com/amaatouq/room-assignment-csop/

Let me know if anything is unclear! I am working with Abdullah and can be reached in Slack also.

### PR DESCRIPTION
**Pull request by hubertusputu1**
Tried to save a players state on intro steps at global file.

## Motivation and Context

#230 

## How Has This Been Tested?

Run a game with 2 batch (two players game), on first player, player stayed on the second instructions, the other finished the intro steps. The first player still stayed on the second instruction. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: lib/globals.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
+var introStates = [];
```
Comment (npaton) [inline lib/globals.js]: Maybe use a {}, key is player ID and values, a states {}.

File: ui/components/InstructionSteps.jsx [hunk 2]
```diff
@@ -1,8 +1,15 @@
 import React from "react";
 import Loading from "./Loading.jsx";
+import { addState, findState } from "../../lib/globals";
```
Comment (npaton) [inline ui/components/InstructionSteps.jsx:3]: I think we skip globals.js entirely and just add a "global" state in this file.

**Review by npaton — APPROVED** [review]

**Review by npaton — APPROVED** [review]
