### PR TITLE
Fixes/admin/change created at into running at batch time #164

### LINKED ISSUE #164: Admin Batch time should be runningAt instead of createdAt
## Expected Behavior

When the Batch is running, in the Admin the time shown in the table (e.g. "10 minutes ago") should be `batch.runningAt`.

## Current Behavior

It's displaying `batch.createdAt`.

## Possible Solution
If the batch has started if should use `batch.runningAt` in that column. Before it's running, I don't know, it should display nothing?

### PR DESCRIPTION
**Pull request by hubertusputu1**
- [x] Changed createdAt into runningAt on batches Admin UI. 
- [x] Sorted the batches based on Abdullah's Comment

## Motivation and Context

#164 

## How Has This Been Tested?

- [x] created batches with different statuses, everything was sorted. 
- [x] createdAt changed into runningAt

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: ui/components/admin/AdminBatches.jsx [hunk 1]
```diff
@@ -93,7 +93,7 @@ export default class AdminBatches extends React.Component {
                 <th>#</th>
                 <th>Status</th>
                 <th>Game Count</th>
-                <th>Created</th>
+                <th>Running At</th>
```
Comment (npaton) [inline ui/components/admin/AdminBatches.jsx]: I think we should call this "Started At" instead.

**Review by npaton — CHANGES_REQUESTED** [review]
Just a quick naming change.
Otherwise, nice to be sorting.
👍

**Review by npaton — APPROVED** [review]
