### PR TITLE
fix: rework on custom newPlayer page #173

### LINKED ISSUE #173: Overriding NewPlayer is too difficult/impossible
Overriding the NewPlayer component is complex. There is still all the consent management and errors and stuff that has nothing to do with the NewPlayer form. The NewPlayer component should only do NewPlayer stuff, so it's easy to override. I think we can easily extract most behavior out of this component into a parent component.

### PR DESCRIPTION
**Pull request by hubertusputu1**
Rework on custom newPlayer Page

## Description

Put the custom component on current NewPlayer, only use the component if the component exist (keep the other logics).

## Motivation and Context

#173 

## How Has This Been Tested?

- [x] tested with custom new player component
- [x] tested without custom component

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: ui/components/NewPlayer.jsx [hunk 1]
```diff
@@ -91,10 +116,19 @@ export default class NewPlayer extends React.Component {
...
+      return (
+        <CustomNewPlayer
+          {...this.props}
+          handleNewPlayer={this.handleNewPlayer}
+        />
+      );
+    }
+
     return (
       <Centered>
```
Comment (npaton) [inline ui/components/NewPlayer.jsx]: Looking good! I was confused at first, but this makes sense. 👍 
I think we should pull out this default form into its own component, so we can point to it as an example implementation for people who want to override with a custom new player component.

**Review by npaton — CHANGES_REQUESTED** [review]

File: ui/components/NewPlayer.jsx (hunk 1 above)
Comment (hubertusputu1) [reply ui/components/NewPlayer.jsx]: Thank you. I agreed, i already extract the form into a single component.

**Review by npaton — APPROVED** [review]
LGTM
