### PR TITLE
Fixes/fix game status on cancelled batch #241 #225

### LINKED ISSUE #225: New Player form hangs
Submitting the player form hangs, nothing happens.

## Expected Behavior

The player should go to the intro steps.

## Current Behavior

Nothing happens. Looking at the websocket, the createNewPlayer rpc is sent, and the player gets created in the DB, but then the playerInfo subscription never updates with the player info.

## Possible Solution

I suspect the initial lobby/batch assignment (after player creation, still inside createNewPlayer) is blocked in the case described here:

> In my admin panel I had a batch that had two games. One was “finished” the other one was “lobby cancelled”.  For some reason, the status of this batch was “running”.  When I cancelled this batch, it seems to work properly now.

## Steps to Reproduce (for bugs)

1. Let a batch have a lobby cancelled (timeout) and no other games, I think

### LINKED ISSUE #241: Cancelling last few games rendered every game cancelled
I had 200 games, with complete randomisation and four different treatments (50 each), Two games had participants who had started but then went away without finishing the games. All the other games were finished. I cancelled these last two games. When I cancelled the last one, it made every game count as cancelled. In the data I have every exitStatus as gameCancelled. (Good thing I saved a final version of the data before that). 

Windows, Firefox, Empirica:core 1.15.3

### PR DESCRIPTION
**Pull request by hubertusputu1**
- Fix game status on cancelled batch
- Fix player form hangs

## Description

- only update status of the game if `finishedAt` doesn't exist
- Set gameLobbies status to `running`

## Motivation and Context

#241 
#225 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by npaton — DISMISSED** [review]

File: api/batches/hooks.js [hunk 1]
```diff
@@ -97,9 +97,25 @@ Batches.after.update(
...
+        { batchId, _id: { $in: unfinishedGameIds } },
+        { $set: { status } },
+        { multi: true }
+      );
+      GameLobbies.update(
+        { batchId, gameId: { $in: unfinishedGameIds } },
+        { $set: { status } },
+        { multi: true }
+      );
+    }
```
Comment (npaton) [inline api/batches/hooks.js]: Instead of searching the unfinished games, shouldn't it check for `status: { $ne: "finished" }`, or maybe rather `status: { $nin: [ "finished", "cancelled", "failed", "custom" ] }`.

**Review by npaton — COMMENTED** [review]
I just added that one comment, but the same idea should probably go for any status change. We should avoid changing any status on games, lobbies or batches if their status is already one of the 4 statuses representing a finished game ("finished", "cancelled", "failed" and "custom").

**Review by npaton — APPROVED** [review]
