### PR TITLE
fix: add missing player attribute onSubmit #93

### LINKED ISSUE #93: Logging Submission Timestamps
It would be useful to have a server-side timestamp when the player presses submit. In the current version of empirica, this can be done either clientside in submit callback, or serverside in the onSubmit callback. Client-side timestamps are unreliable and out of sync with the server. Unfortunatlely, the round object passed to onSubmit server is not the player-round and accessing the player.round object does not allow calling player.round.set("SubmittedAt", new Date). 

## Expected Behavior
Ideally, it would be possible to call player.round.set("foo", bar) in the onSubmit callback. 

## Current Behavior
Currently doing so produces an error (set not defined)

## Possible Solution
Passing the player-round object would fix the issue, I believe. 

## Steps to Reproduce (for bugs)
This can be reproduced by making a call as described above.

### PR DESCRIPTION
**Pull request by hubertusputu1**
## Description

added missing stage and round object on player inside onSubmit 

## Motivation and Context

https://github.com/empiricaly/meteor-empirica-core/issues/93

## How Has This Been Tested?

- logged the player.round and player.stage inside Empirica.onSubmit callback, and both attribute existed
- set attribute on player.round.set and player.stage.set
- get attribute on player.round.get and player.stage.get

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: api/server/onsubmit.js [hunk 1]
```diff
@@ -49,5 +49,8 @@ export const callOnSubmit = params => {
     augmentPlayerStageRound(player, player.stage, player.round, game);
   });
 
+  player.stage = _.extend({}, stage);
+  player.round = _.extend({}, round);
+
```
Comment (npaton) [inline api/server/onsubmit.js:55]: Does this require an augmentPlayerStageRound call here? Otherwise calling player.stage.set() will add the value to the root stage, not the player-stage, no?

**Review by npaton — CHANGES_REQUESTED** [review]

File: api/server/onsubmit.js (hunk 1 above)
Comment (hubertusputu1) [reply api/server/onsubmit.js:55]: yes it does, my bad, i forgot to add the augmentPlayerStageRound

**Review by npaton — APPROVED** [review]
