### PR TITLE
Fixes/bulk operations db 90

### LINKED ISSUE #90: Game starts slow for games with many rounds / stages
## Current Behaviour
We found the game creation being bottlenecked by the database performance for games with many rounds and/or many stages. In our setting with 80 rounds a 3 stages and an external database, game creation could take up to 40seconds. The reason seems to be a large number of individual inserts/updates during creation.

https://github.com/empiricaly/meteor-empirica-core/blob/f01ca69d3078fc8efd25129a1ac23e3f0cb34d22/api/games/create.js#L187-L235

## Possible Solution
Using bulk operations on the database.

### PR DESCRIPTION
**Pull request by hubertusputu1**
## Description

changing normal insertion inside rounds creation into bulk operations

## Motivation and Context

Issue: https://github.com/empiricaly/meteor-empirica-core/issues/90
This change reduce the duration needed of rounds creation. 

## How Has This Been Tested?

test environment: 100 rounds, 100 stages each, 1 player
before changes: it takes 26 - 30s 
after changes: it takes 5 - 8s

test environment: 100 rounds, 5 stages each, 10 players
before changes: it takes 8 - 10s
after changes: it takes less than 5s

rounds, stages, player_rounds, player_stages collections also has been checked that still insert the same docs. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: api/games/create.js [hunk 1]
```diff
@@ -184,56 +184,141 @@ export const createGameFromLobby = gameLobby => {
...
+        {
+          gameId,
+          index,
+          _id: Random.id(),
+          createdAt: new Date(),
+          updatedAt: new Date()
+        },
+        round
+      ),
+      insertOption
```
Comment (npaton) [inline api/games/create.js:214]: I don't think these insertOption apply to Bulk ops, those options have to do with SimpleSchema, which is not part of Mongo.

**Review by npaton — CHANGES_REQUESTED** [review]
LGTM. Just check on that insertOption, I don't think it's necessary.
And just make sure you have the exact same docs inserted.
Can you notice a marked performance improvement. You might need to try on a high round/stage game to feel the effect on a local dev setup. Let me know what kind of improvement you're seeing. Thanks!

**Comment by hubertusputu1** [comment]
@npaton , I did the test local dev setup. this is what i got:

test environment: 100 rounds, 100 stages, 1 player
before changes: it takes 26 - 30s
after changes: it takes 5 - 8s

i also checked that bulk insertions have exact same docs on the db.

**Comment by npaton** [comment]
Great! Could I ask you to do one more test, for performance and verification of the records. Just to be sure, please run one test with multiple players: 100 rounds, 5 stages each, 10 players. I just want to make sure we have all player-rounds and player-stages created. And we'll post the performance improvements for both of these scenarios.
Otherwise, that's it, one more test, and it looks like we'll be ready to merge. Great stuff!

**Comment by hubertusputu1** [comment]
@npaton i did the test that you requested:

test environment: 100 rounds, 5 stages each, 10 players
before changes: it takes 8 - 10s
after changes: it takes less than 5s

rounds, stages, player_rounds, player_stages collections also has been checked that still insert the same docs.

**Review by npaton — APPROVED** [review]

**Comment by npaton** [comment]
Great! Feel free to merge, and let the corresponding ticket know that the improvement will appear in the upcoming next version of Empirica.
