### PR TITLE
fix: add exitReason and fix CSV import #223

### LINKED ISSUE #223: Add player.exitReason to export!
Somehow `player.exitReason` is not extracted.

### PR DESCRIPTION
**Pull request by hubertusputu1**
Fix CSV import and add player.exitReason to export 

## Motivation and Context

#223 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: startup/server/export.js [hunk 1]
```diff
@@ -202,6 +202,10 @@ WebApp.connectHandlers.use("/admin/export", (req, res, next) => {
         case "csv":
           const out = [];
           keys.forEach(k => {
+            if (k === "urlParams" || k === "lastLogin") {
+              console.log(k);
+              console.log(data[k]);
+            }
```
Comment (npaton) [inline startup/server/export.js]: debug logs

**Review by npaton — CHANGES_REQUESTED** [review]

**Review by npaton — APPROVED** [review]
