### PR TITLE
fix: game end when last player exit #74

### LINKED ISSUE #74: Game should end when last player has exited
After calling `player.exit("some reason")`, if there are no more players in the Game the player exited, the game should end immediately, and with a clean finished status (maybe with a "finished early" flag).

### PR DESCRIPTION
**Pull request by hubertusputu1**
## Description

adding condition to end the game immediately when last player exit

## Motivation and Context

https://github.com/empiricaly/meteor-empirica-core/issues/74

## How Has This Been Tested?

tested with single and multiplayer, the game ended immediately after the last player has exit. The status on the batches page changed from "running" into "finished"

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: api/game-lobbies/game-lobbies.js [hunk 1]
```diff
@@ -52,6 +52,13 @@ GameLobbies.schema = new SimpleSchema({
     index: 1
   },
 
+  endReason: {
+    label: "Ended Reason",
+    type: String,
+    optional: true,
+    regEx: /[a-zA-Z0-9_]+/
```
Comment (npaton) [inline api/game-lobbies/game-lobbies.js:59]: This regexp does not seems to allow spaces, yet below I see `endReason: "finished early"`. Do I understand this wrong? :)

**Review by npaton — CHANGES_REQUESTED** [review]

File: api/game-lobbies/game-lobbies.js (hunk 1 above)
Comment (hubertusputu1) [reply api/game-lobbies/game-lobbies.js:59]: yes, space shouldn't be allowed, sorry my bad.

**Review by npaton — APPROVED** [review]
